id: s2222
name: '26_e22'
version: 1.0.9
author: '0'
icon: app.png
desc: '0'
files:
  - camera_calibration.py
  - jiuzheng.py
  - main.py
  - runtime_pipeline.py
  - task_pipeline.py
  - make_demo_plan.py
  - motion_protocol.py
  - piece_vision.py
  - pixel_to_pulse_calibration.py
  - puzzle_solver_v3.py
  - puzzle_solver.py
  - texture_matcher.py
  - uart0_test.py
